### ISSUE TITLE
Propose a logo for this project

### ISSUE THREAD

**Issue by hax** [fanmingfei/array-reverse-ios12#11]
![ios-12-reverse](https://user-images.githubusercontent.com/159840/45736779-8a4ad180-bc1e-11e8-9022-b58935f026eb.png)

**Comment by terrykingcha** [comment]
Nice!,But how to set the logo for this project?

**Comment by Justineo** [comment]
![image](https://user-images.githubusercontent.com/1726061/45738252-7ef9a500-bc22-11e8-86d7-c10b6bac7457.png)

Array, reverse and iOS 12 all-in-one here.

**Comment by justjavac** [comment]
@terrykingcha put it in readme.md

**Comment by terrykingcha** [comment]
@justjavac Got IT

**Comment by fanmingfei** [comment]
done

**Comment by hax** [comment]
一丝姐姐 created a gif version... @yisibl could you upload it to here?

**Comment by yisibl** [comment]
@hax No problem.
When I have time, I can submit the PR of the HTML source file, skr skr…
![1212](https://user-images.githubusercontent.com/2784308/45812030-411f7e00-bd01-11e8-8b84-93cddc0a4c66.gif)
