### ISSUE TITLE
Tests fail when run on Safari 12.0 Mac

### ISSUE THREAD

**Issue by pwagland** [fanmingfei/array-reverse-ios12#12]
When running the tests at https://fanmingfei.github.io/array-reverse-ios12/tests/

I get:

> QUnit 2.6.2; Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15
> 5 tests completed in 6 milliseconds, with 1 failed, 0 skipped, and 0 todo.
> 12 assertions of 15 passed, 3 failed.

I have noticed that this only fails on every second run. So it looks like when the page is reloaded something is not being reset correctly?

**Comment by fanmingfei** [comment]
Yes, Safari 12.0 Mac has the bug. But currently the lib is use for iOS 12. I will fix Safari 12.0

**Comment by fanmingfei** [comment]
have try

**Comment by pwagland** [comment]
This works for me now. Thanks for the quick update!
