### ISSUE TITLE
What if user has already opened a page not polyfilled?

### ISSUE THREAD

**Issue by cnzh2992** [fanmingfei/array-reverse-ios12#7]
Thanks for the awesome polyfill. After some tests I found the array will be consistently reversed if I enter origin.html first. My test case is:

1. Enter origin.html, page alerts "1,2,3,4";
2. Enter fixed.html, page alerts "4,3,2,1"
3. Refresh fixed.html again, page still alerts "4,3,2,1"

Is it the expected behavior, or are there any workaround? Thanks!

**Comment by hax** [comment]
If any code trigger the bug already called before this patch, a related store of the array initializer may already corrupted, so it may still be buggy. You could only refresh much times to expect the memory will be finally pruned.

I have no idea how to fix that...

**Comment by hax** [comment]
The good news is: it seems won't affect cross-origin scripts. So if you fix all pages of your site, you will not be affected by other site.
